<center> <h1>Example Problems CPE 4040</h1> </center>

Julian Duran                                                                        March 3, 2020

*Solve 6 out of 7 questions in the cells provided under each problem. Save your notebook addin your first name and last name at the end of the filename and submit.*

1- Write a Python code which asks two numbers from the user, calculates the product and print the result. Create a function to calculate the product and return the result value.<br>
i.e. <br>
First Number:12 <br>
Second Number:23 <br>
10 * 23 = 230

In [7]:
x = input("Please enter a first number: ")
y = input("Please enter a second number: ")

z = int(x)*int(y)
print("\nThe product of your numbers is: ", z)

Please enter a first number: 12
Please enter a second number: 23

The product of your numbers is:  276


2- Create 20 random integers in an array which has the numbers between 1 and 100 (includes both 1 and 100). Pick and sort first the even numbers then the odd numbers in ascending order and print the final array. (i.e. [1 3 51 77 4 12 44 82])

In [70]:
import numpy as np

arr = np.random.randint(1,100,20)
print(arr)

arreven = []
arrodd = []
for i in arr:
    remain = int(i)%2
    if (remain == 0):
        arreven.append(i)
    elif (remain == 1):
        arrodd.append(i)
arreven.sort()        
print("\nThe array with even values in ascending order is: ",arreven)
arrodd.sort()
print("The array with odd values in ascending order is: ", arrodd)


[29 32 90 23 56 71 93 13 30 96 87 85 51 22 53 33 70 57 73 24]

The array with even values in ascending order is:  [22, 24, 30, 32, 56, 70, 90, 96]
The array with odd values in ascending order is:  [13, 23, 29, 33, 51, 53, 57, 71, 73, 85, 87, 93]


3- Write a simple number guessing game Python program. In this code, generate a random integer between 1-10 (both included) and ask the user to guess the number in three attempts. 
Print appropriate responses to the user such as "You won!" or "You failed"

In [4]:
import random


number = random.randint(0,100)
print(number)
count = 0
while count < 3:
    Guess = input("Guess what the randomly generated number is: ")
    if (int(Guess) == number):
        print("You Won!")
        break
    else: 
        if (count == 2):
            print("You failed!")
        else:
            print("You failed! Try again!")
    count += 1
            


81
Guess what the randomly generated number is: 5
You failed! Try again! Tries left:  2
Guess what the randomly generated number is: 3
You failed! Try again! Tries left:  1
Guess what the randomly generated number is: 2
You failed!


4- Write a Python code that asks a string from the user and prints only the lower case letters in that string.

In [123]:
response = input("Please enter a string: ")
out = ""
for i in response:
    if (i == i.lower()):
        out += i
        
print(out)

Please enter a string: Hello PyThon WoRld
ello yhon old


5- Write a function which takes a string as an argument and return true if the string is symmetrical (i.e. "level") and return false otherwise. 

6- Create a 4x7 2D array with random floating point positive numbers. Subtract the mean value of each row from the corresponding row. 

In [122]:
import numpy as np

a1 = np.random.rand(4,7)
print ("Array generated with random values: \n", a1)
b = a1.mean(axis = 1)
b = b.reshape(4,1)
print("\nThe means of each row of array a1 in an array of shap 4X1: \n", b)
print("\nWhen subtracting the means of each row with the corresponding row you get: \n", np.subtract(a1,b))

Array generated with random values: 
 [[0.73031147 0.35306701 0.7951654  0.1219191  0.40063768 0.00732095
  0.03698566]
 [0.96942637 0.51916191 0.9999488  0.97676862 0.47549137 0.24329314
  0.82354678]
 [0.96772427 0.53195824 0.47360203 0.15826956 0.21132248 0.81228241
  0.15549142]
 [0.03144801 0.9926796  0.70375832 0.62597282 0.92847637 0.11239569
  0.53578751]]

The means of each row of array a1 in an array of shap 4X1: 
 [[0.3493439 ]
 [0.71537671]
 [0.47295006]
 [0.56150262]]

When subtracting the means of each row with the corresponding row you get: 
 [[ 0.38096758  0.00372312  0.4458215  -0.2274248   0.05129378 -0.34202294
  -0.31235824]
 [ 0.25404965 -0.1962148   0.28457209  0.26139191 -0.23988534 -0.47208357
   0.10817006]
 [ 0.49477421  0.05900818  0.00065197 -0.3146805  -0.26162758  0.33933235
  -0.31745864]
 [-0.53005461  0.43117698  0.1422557   0.0644702   0.36697375 -0.44910693
  -0.02571511]]


7- Create an array with 10 random integers. Write a Python script which replaces the minimum number with the maximum number in the array. 

In [35]:
import numpy as np

arr = np.random.randint(0,100,10)
print(arr)
print("\nThe max value in the array is: ", arr.max())
print("The min value in the array is: ", arr.min())

arr[arr.argmax()] = min(arr)
print("\nWhen replacing the largest value in the array with the smallest, the resulting array is:")
print(arr)

[74 19 71 50 12 54 88 71 22 13]

The max value in the array is:  88
The min value in the array is:  12

When replacing the largest value in the array with the smallest, the resulting array is:
[74 19 71 50 12 54 12 71 22 13]
